docs/installation/Setup-OpenFunction-Serving-with-Knative.md

1. Change the In-page link destination title to ```Installation when having poor network connectivity to GitHub/Googleapis```
for issue #13 

fix In-page link

---

config/samples/core_v1alpha1_function.yaml
pkg/controllers/build.go

1. By exposing the "gitInitImage" configuration item, the ```Builder``` can control the "gitInitImage" parameter of the ```git-clone``` task.
2. Modified the configuration in sample ```core_v1alpha1_function.yaml``` to add the ```spec.source.gitInitImage``` property. If Tekton is used as the Builder, leaving this empty means useing the default image which is named: ```gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/git-init:v0.21.0``` while you can use another image instead of it.

expose the 'gitInitImage' configuration item

---

config/bundle.yaml
config/crd/bases/core.openfunction.io_builders.yaml
config/crd/bases/core.openfunction.io_functions.yaml
pkg/apis/v1alpha1/builder_types.go
pkg/apis/v1alpha1/function_types.go
pkg/controllers/build.go
pkg/controllers/function_controller.go

1. Add ```FuncSource``` parameter and set it omitempty.
2. ```FuncSource``` means the name of function file such as ```main.py``` for python.
3. **Unset it** when language function framework dose not support it.(```nodejs```, e,g.)

Add FuncSource parameter

---

README.md
config/samples/function-sample.yaml

1. Change default builder to "openfunction/gcp-builder:v1"

Change default builder to "openfunction/gcp-builder:v1"

---

docs/proposals/202105_add_client_tool.md

OpenFunction currently lacks a simple and efficient command line tool to manage 
its resources. 
Having an effective command line tool allows users to focus on the core functionality 
of the OpenFunction, while also presenting the relationship between the OpenFunction 
and its dependent components in a more abstract and friendly way to the user.
Fixes #29 

proposal: add client tool

---

README.md
docs/installation/Setup-OpenFunction-Serving-with-Knative.md
hack/deploy-tekon-and-knative.sh

Track the v0.23.0 version of Knative, fix default domain by modify xip.io to sslip.io.

Track the v0.23.0 version of Knative

---

cmd/main.go
go.mod
pkg/controllers/build.go
pkg/controllers/builder_controller.go
pkg/controllers/function_controller.go
pkg/controllers/serving_controller.go

Currently, the function controller does not watch the builder and serving, so the function controller cannot recreate them when the builder or serving is deleted. 
This pr make the function controller owns the builder and serving, thereby solving the following problems:
- Recreate the builder when the builder is deleted and the build is not completed. Rebuild can be achieved by deleting the builder when the build fails.
- Recreate the serving after serving is modified or deleted.
- If the parameters of the function are modified, the rebuild will be triggered automatically, and the serving will be re-run after the build is completed. It is easy to trigger rebuild when the function code is modified by modifying the parameter of the function, …

make the function controller owns serving an builder

---

cmd/main.go
go.mod
go.sum
pkg/controllers/build.go
pkg/controllers/builder_controller.go
pkg/controllers/function_controller.go
pkg/controllers/serving_controller.go
pkg/util/error.go
pkg/util/hash.go

Replace cache builder and serving with cache function, the cache will be updated after function reconciles successful, and deleted after the function is deleted.
The following figure shows the complete cache mechanism and the logic of determining whether the builder and serving need to be updated through the cache.

Optimize the cach mechanism of the function controller

---

docs/proposals/202107_add_event_framework.md

We consider introducing an event framework that will have the following key features:
- Adapt multiple event sources based on the Dapr
- Drive the OpenFunction runtime (make OpenFunction event-driven)
- The event framework itself can also be served by OpenFunction

Add OpenFunction event framework proposal

---

README.md
apis/core/v1alpha1/zz_generated.deepcopy.go
controllers/events/event.go
docs/concepts/OpenFunction-events-framework.md

1. Adjusted the Readme and added a section for Events CRDs and a link to jump to Events related documentation
2. Adjusted the name template of the eventbus component generated by EventSource and Trigger

Update events framework docs and eventbus name template

---

Dockerfile
config/bundle.yaml
config/rbac/role.yaml
controllers/events/eventsource_controller.go
controllers/events/trigger_controller.go

**Dockerfile**
If we use the `nonroot` user in the image and set `runAsNonRoot` in the container, then the following exception will occur:
```
Error: container has runAsNonRoot and image has non-numeric user (nonroot), cannot verify user is non-root
```
**RBAC**
Added RBAC rules for watching EventBus and ClusterEventBus in the ApiGroup "events.openfunction.io"

fix: Dockerfile && rbac configurations

---

hack/deploy.sh

We may need to keep the dapr version at v1.3.1 for now, as this is a more stable version?

Adjust the dependent Dapr version to v1.3.1

---

Makefile
apis/core/v1alpha2/builder_types.go
apis/core/v1alpha2/function_types.go
apis/core/v1alpha2/serving_types.go
apis/core/v1alpha2/zz_generated.deepcopy.go
config/bundle.yaml
config/crd/bases/core.openfunction.io_functions.yaml
config/crd/bases/core.openfunction.io_servings.yaml
config/manager/manager.yaml
controllers/core/function_controller.go
go.sum
pkg/constants/constants.go
pkg/core/serving/knative/servingrun.go
pkg/core/serving/openfuncasync/servingrun.go
pkg/util/utils.go

Signed-off-by: wanjunlei <wanjunlei@kubesphere.io>
This pr is for issues #165 and #169 .
Users can add labels and annotations to the pod that runs the functions like this.
```
apiVersion: core.openfunction.io/v1alpha2
kind: Function
metadata:
name: function-sample-serving-only
spec:
version: "v1.0.0"
image: "openfunctiondev/sample-go-func:latest"
#port: 8080 # default to 8080
serving:
labels:
app: openfunction
annotations:
cluster-autoscaler.kubernetes.io/safe-to-evict: "true"
runtime: Knative
template:
containers:
- name: function
imagePullPolicy: Always
```
The `app.kubernetes.io/version` label will be added to the pod that runs the functions by default.
The `app.kubernetes.io/name` label is only added to the openfunction controller.

support for adding labels and annotations to worklod

---

config/samples/function-bindings-sample-serving-only.yaml
config/samples/function-knative-with-dapr-serving-only.yaml
config/samples/function-pubsub-sample-serving-only.yaml

remove the imageCredentials in e2e samples

---

apis/events/v1alpha1/eventsource_types.go
config/bundle.yaml
config/crd/bases/events.openfunction.io_eventsources.yaml
controllers/events/event.go
controllers/events/eventsource_controller.go
controllers/events/trigger_controller.go

1. fix issue #164 
2. when EventSource is configured with the `spec.sink` field, use `spec.sink.uri` to carry the final URL address.

fix issue #164

---

.github/workflows/main.yaml
Makefile
config/bundle.yaml
config/cert/kustomization.yaml
config/cert/webhook-server-cert.yaml
config/crd/kustomization.yaml
config/crd/patches/cainjection_in_builders.yaml
config/crd/patches/cainjection_in_clustereventbus.yaml
config/crd/patches/cainjection_in_domains.yaml
config/crd/patches/cainjection_in_eventbus.yaml
config/crd/patches/cainjection_in_eventsources.yaml
config/crd/patches/cainjection_in_functions.yaml
config/crd/patches/cainjection_in_servings.yaml
config/crd/patches/cainjection_in_triggers.yaml
config/crd/patches/webhook_in_functions.yaml
config/crd/patches/webhook_in_servings.yaml
config/default/kustomization.yaml
config/default/webhookcainjection_patch.yaml
config/webhook/manifests.yaml
docs/development/development-workflow.md
hack/generate-cert.sh

I think we can remove the dependency on the cert-manager. We can use `generate-cert.sh` to generate the information we need for the certification process.
This requires us to go into the `hack` directory and manually execute the `bash generate-cert.sh` command before `make manifests`. This action will automatically replace the certification information in the relevant files.

use `generate-cert.sh` to generate caBundle and tls.* files

---

.github/workflows/main.yaml
Makefile
docs/development/development-workflow.md
test/async-runtime/bindings/expected.data.yaml
test/async-runtime/bindings/manifests.yaml
test/async-runtime/bindings/verify.sh
test/async-runtime/e2e.yaml
test/async-runtime/pubsub/expected.data.yaml
test/async-runtime/pubsub/manifests.yaml
test/async-runtime/pubsub/verify.sh
test/e2e.yaml
test/e2e_env
test/events/e2e.yaml
test/events/expected.data.yaml
test/events/manifests.yaml
test/events/verify.sh
test/kafka.yaml
test/kind.yaml
test/knative-runtime/e2e.yaml
test/knative-runtime/knative-dapr/expected.data.yaml
test/knative-runtime/knative-dapr/manifests.yaml
test/knative-runtime/knative-dapr/verify.sh
test/knative-runtime/knative/expected.data.yaml
test/knative-runtime/knative/manifests.yaml
test/knative-runtime/knative/verify.sh
test/plugin/e2e.yaml
test/plugin/expected.data.yaml
test/plugin/manifests.yaml
test/plugin/verify.sh

1. add `make e2e-knative` command for knative-runtime e2e testing.
2. add `make e2e-async` command for async-runtime e2e testing.
3. add `make e2e-plugin` command for plugin functionality e2e testing.
4. add `make e2e-events` command for events-framework functionality e2e testing.
5. add a one-click `make e2e-all` command for all the above e2e tests.
6. add docs.

Add e2e testing ability for local environments

---

pkg/core/serving/knative/servingrun.go

Use "autoscaling.knative.dev" instead of the const "knativeAutoscalingPrefix".

Use fixed strings instead of `knativeAutoscalingPrefix`

---

config/bundle.yaml
controllers/events/eventsource_controller.go
pkg/util/utils.go

Signed-off-by: xjl123456 <1576696610@qq.com>
There is no sink when creating the EventSource crd
```
apiVersion: events.openfunction.io/v1alpha1
kind: EventSource
metadata:
name: my-eventsource
spec:
logLevel: "2"
cron:
default-cron:
schedule: '@every 5s'
eventBus: default
```
openfunction controller error
```
2022-12-14T02:20:26.733Z        INFO    controllers.EventSource Updated status on EventSource   {"EventSource": "xjl/my-eventsource", "resource version": "4943504"}
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x16fcb75]
goroutine 1029 [running]:
github.com/openfunction/controllers/events.(*EventSourceReconciler).createOrUpdateEventSource(0xc0003b4f00, 0x1cc29b8, 0xc0008fafc0, 0x1ccc760, …
```

Add non null judgment for sink

---

pkg/core/serving/common/common.go

Set the scope of the dapr component when creating it, so that the dapr component can only be accessed by function.

set scopes when create dapr components
