pkg/controllers/build.go
pkg/controllers/build_task_templates.go
pkg/controllers/builder_controller.go
pkg/controllers/function_controller.go

Upgrade to tekton buildpacks v0.3

---

cmd/main.go
go.mod

Enter Serving Phase only when the build is successful

---

cmd/main.go
pkg/apis/v1alpha1/function_types.go

Update function status when the build is failed

---

README.md
docs/roadmap.md

Add roadmap

---

config/bundle.yaml
config/crd/bases/core.openfunction.io_builders.yaml
config/crd/bases/core.openfunction.io_functions.yaml
config/samples/function-sample.yaml
pkg/apis/v1alpha1/builder_types.go
pkg/apis/v1alpha1/function_types.go
pkg/apis/v1alpha1/zz_generated.deepcopy.go
pkg/controllers/build.go
pkg/controllers/function_controller.go

Move function name and type to params

---

config/samples/buildpacks/sample-apps-java-maven.yaml
config/samples/buildpacks/sample-apps-kotlin-gradle.yaml

Signed-off-by: benjaminhuo <benjamin@yunify.com>

Add sample app from github.com/buildpacks/samples

---

config/samples/function-sample.yaml
config/samples/gcp/sample-function-framework-go.yaml

1. Modify the the environment variable parameter in openfunction/gcp-builder:v1
2. Add gcp buildpack sample

change builder params' name & add gcp sample

---

docs/roadmap.md

Adjust roadmap

---

docs/installation/Setup-OpenFunction-Builder-with-Tekton.md
docs/installation/Setup-OpenFunction-Serving-with-Knative.md

1. proxy images of v0.24.0 and update the docs

update tekton pipeline to v0.24.0

---

hack/deploy-tekon-and-knative.sh

replace xip.io to nip.io

---

README.md

Change README for serving

---

Makefile

Add version info

---

README.md

Adjust installation guide

---

README.md

Update install guide

---

README.md

Add a simple guide for using node ip as the external ip of Knative network layer

Add a simple guide

---

docs/proposals/202105_add_function_framework.md

proposal: add function framework
Signed-off-by: laminar <fangtian@yunify.com>

Add a proposal of "Add function framework"

---

README.md

Add Community info to README

---

config/bundle.yaml
config/crd/bases/core.openfunction.io_functions.yaml
config/rbac/role.yaml
config/samples/function-producer-sample.yaml
config/samples/function-subscriber-sample.yaml
go.mod
go.sum
pkg/controllers/builder_controller.go
pkg/controllers/function_controller.go
pkg/controllers/serving_controller.go

update clusterole for OpenFuncAsync runtime

---

README.md

1. Add instruction for OpenFuncAsync

Add instruction for OpenFuncAsync

---

CHANGELOG.md
Makefile
RELEASE.md

Add docs to launch a new release

---

CHANGELOG.md
README.md

Init release v0.2.0

---

README.md

Update uninstall cmd

---

README.md
docs/concepts/OpenFunction-events-framework.md

Ajust OpenFunction events descriptions

---

config/bundle.yaml
config/crd/bases/core.openfunction.io_builders.yaml
config/crd/bases/core.openfunction.io_functions.yaml

update crd yaml

---

docs/concepts/OpenFunction-events-framework.md
docs/proposals/202108_event_framework_trigger_condition.md

1. Add a proposal of the trigger condition
2. Update event framework docs for we have improved the spec for event framework CRD

docs: Add trigger condition proposal && update event framework docs

---

README.md
docs/roadmap.md
hack/deploy.sh

Update Readme/Roadmap/Intall Script

---

hack/deploy.sh

tekton-pipeline v0.23.0 -> v0.27.1
tekton-triggers v0.13.0 -> v0.15.1
tekton-dashboard v0.16.0 -> v0.19.0
knative-serving v0.23.0 -> v0.24.0
keda v2.2.0 -> v2.4.0

Update the version of dependent components

---

CHANGELOG.md
README.md
docs/roadmap.md

-  Add OpenFunction Events: OpenFunction's own event management framework.
-  Support using ShipWright as Builder backend to build functions or apps.
-  Build and serving can be launched separately.
-  Support running an application (container image) as a serverless workload directly.

Release 0.3

---

README.md
RELEASE.md

Release-0.3-fix

---

README.md

Update meeting info

---

README.md

Update meeting info (#112)

---

README.md

Added two simple function examples to the **readme**

Add function examples

---

README.md

Typo: fix indentation error in readme

---

docs/roadmap.md

Add function tracing to roadmap

---

CODE_OF_CONDUCT.md
OWNERS

Signed-off-by: FeynmanZhou <feyman@kubesphere.io>

add CODE_OF_CONDUCT and OWNERS

---

Dockerfile
apis/core/v1alpha2/function_conversion.go
config/bundle.yaml
config/strategy/strategy.yaml
controllers/core/function_controller.go
pkg/core/builder/shipwright/builderrun.go

Fix bug build app with Dockerfile failed

Fix bug build app with Dockerfile failed

---

README.md
docs/concepts/Components.md

docs: Optimization of readme

---

docs/proposals/202112_support_function_tracing.md

Add function tracing proposal

---

.github/workflows/e2e-test.sh
.github/workflows/main.yaml
config/strategy/strategy.yaml

Signed-off-by: wanjunlei <wanjunlei@kubesphere.io>

fix bug ci run failed

---

.github/workflows/main.yaml
.github/workflows/push-image.yaml

Signed-off-by: wanjunlei <wanjunlei@kubesphere.io>

build and push image when pr megerd or tag created

---

CHANGELOG.md
RELEASE.md

Add changelog for v0.5.0

---

README.md

docs: update the documentation of installing OpenFunction via ofn

---

docs/proposals/202112_support_function_tracing.md

Adjust tracing plugin proposal

---

docs/roadmap.md

Adjust roadmap for 2022 Q1~Q2

---

README.md

Adjust compatibility matrix

---

apis/events/v1alpha1/eventsource_types.go
controllers/events/event.go
controllers/events/event_test.go

Signed-off-by: zhangwei <zhangwei24@apache.org>
Like this:
```yaml
spec:
sink:
ref:
apiVersion: core.openfunction.io/v1alpha2
kind: Function
name: function-sample
namespace: default
```

sink.ref support Function

---

pkg/core/builder/shipwright/builderrun.go

Please refer to this issue: https://github.com/OpenFunction/OpenFunction/issues/219

fix(buildrun): Enable buildrun to generate sa by default

---

README.md

docs: update function samples in readme.

---

.github/workflows/e2e-test.sh
.github/workflows/main.yaml
apis/core/v1alpha2/function_conversion.go
config/samples/function-bindings-sample-serving-only.yaml
config/samples/function-kafka-quick.yaml
config/samples/function-knative-with-dapr-serving-only.yaml
config/samples/function-pubsub-sample-serving-only.yaml

add e2e test for knative-dapr, async-bindings case

---

apis/core/v1alpha2/serving_conversion.go

The case of knative-dapr will not be handled in v1alpha2.

---

README.md

docs: change the latest http function signatures

---

README.md

Adjust meeting info

---

RELEASE.md

Adjust the release guide

---

CHANGELOG.md
Makefile
README.md
RELEASE.md
config/bundle.yaml
config/configmap/openfunction-config.yaml
config/crd/bases/core.openfunction.io_functions.yaml
config/crd/bases/core.openfunction.io_servings.yaml
docs/roadmap.md

Add release docs for v0.6.0

---

.github/workflows/e2e-test.sh
config/samples/events-handlers-sample-serving-only.yaml
config/samples/function-bindings-sample-serving-only.yaml
config/samples/function-knative-with-dapr-serving-only.yaml
config/samples/function-pubsub-sample-serving-only.yaml
config/samples/function-sample-serving-only.yaml
config/samples/function-with-plugins-serving-only.yaml
pkg/core/serving/common/common.go
pkg/core/serving/common/functioncontext.go

Change field "functionPluginsTracing.Enable" to "functionPluginsTracing.Enabled"

---

RELEASE.md

Add release item for v0.6.0

---

README.md
docs/faq/README.md

Create the FAQ docs and add two questions:
1. How to use private image repositories in OpenFunction?
2. How to access the Knative-runtime function without introducing a new ingress controller?

Add the FAQ

---

docs/roadmap.md

correct typo

---

code-of-conduct.md

Add CNCF Community Code of Conduct

---

docs/concepts/OpenFunction-events-framework.md

add MQTT eventsource to the docs

---

README.md

Change slack to openfunction@slack.cncf.io

---

README.md

Add discord server

---

go.mod
go.sum
pkg/core/serving/common/common.go

* updated yaml pkg from v2 to v3
closes https://github.com/OpenFunction/OpenFunction/issues/298

refactor(deps): update yaml pkg

---

Makefile
config/samples/function-sample-build-only.yaml
config/samples/function-sample.yaml

modified function samples's sourceSubPath to match https://github.com/OpenFunction/samples.git
updated kustomize version to include this pr https://github.com/kubernetes-sigs/kustomize/pull/4387

modified function samples's sourceSubPath & updated kustomize version

---

README.md

modify the install and uninstall sections in readme.md

---

README.md

Move guide from readme to openfunction.dev

---

README.md

Move comminity call info to the community repo

---

docs/proposals/202207-openfunction-gateway.md

update gateway prososal

---

docs/proposals/202207-openfunction-gateway.md

update gateway prososal image

---

config/gateway/default-gateway.yaml
config/samples/function-sample-with-host-based-route.yaml
config/samples/function-sample-with-path-based-route.yaml
config/samples/gateway-sample.yaml
controllers/networking/gateway_controller.go

add samples to gateway & improve gateway controller compatibility

---

hack/deploy.sh

update deploy.sh to adapt latest version of contour

---

.github/stale.yaml

Add stale app

---

.github/stale.yaml
apis/core/v1beta1/function_types.go
config/bundle.yaml
config/crd/bases/core.openfunction.io_functions.yaml

update Function Address printcolumn: External to Internal

---

controllers/core/function_controller.go

In order to facilitate the upgrade.

compatible with existing old version functions

---

CHANGELOG.md
RELEASE.md

Adjust release docs for v0.7.0

---

CHANGELOG.md

adjust changelog for release v0.7.0-rc.0

---

CHANGELOG.md

adjust the functions-framework-nodejs part of the changelog

---

README.md

Fixed the slack channel link in the readme section

(#355)fixed the link of slack in readme

---

.gitignore
docs/proposals/20220919-one-dapr-sidecar-per-function.md

add one-dapr-sidecar-per-function proposal

---

.github/release-drafter.yml
apis/core/v1alpha2/function_conversion.go
apis/core/v1alpha2/serving_conversion.go
apis/core/v1beta1/function_webhook.go
config/configmap/openfunction-config.yaml
controllers/core/function_controller.go
controllers/events/eventsource_controller.go
controllers/events/trigger_controller.go
controllers/networking/gateway_controller.go
go.mod
pkg/constants/constants.go
pkg/core/serving/common/common.go
pkg/core/serving/knative/servingrun.go
pkg/core/serving/openfuncasync/servingrun.go

- support dapr proxy, issue: https://github.com/OpenFunction/OpenFunction/issues/360
- fix https://github.com/OpenFunction/OpenFunction/issues/366
- fix https://github.com/OpenFunction/OpenFunction/issues/368
- fix https://github.com/OpenFunction/OpenFunction/issues/310

support dapr-proxy & bugfix

---

CHANGELOG.md
RELEASE.md

adjust changelog for release v0.8.0-rc.0

---

CHANGELOG.md

Adjust changelog for OpenFunction v0.8.0

---

controllers/core/function_controller.go
pkg/core/serving/knative/servingrun.go
pkg/core/serving/openfuncasync/servingrun.go

Fixes https://github.com/OpenFunction/OpenFunction/issues/378 https://github.com/OpenFunction/OpenFunction/issues/380

Adjust the owner of the async function service & the DAPR_HOST env var

---

README.md

Update gateway api status

---

docs/proposals/202211-integration-with-kubevela.md

Signed-off-by: fangtian <fangtian@kubesphere.io>

docs: add proposal about integration with KubeVela

---

README.md

Adjust architecture image size

---

OWNERS

Adjust owner

---

docs/proposals/20230424-unify-the-definition-of-functions.md

Add proposal to unify function definition

Add proposal to unify function definition

---

apis/core/v1beta2/function_webhook.go
apis/core/v1beta2/serving_types.go

Allow the user not to set the trigger, the controller will automatically fill in the http trigger

use http trigger as the default trigger

---

config/bundle.yaml
config/rbac/role.yaml
controllers/core/builder_controller.go
controllers/core/function_controller.go
controllers/core/serving_controller.go
controllers/networking/gateway_controller.go
main.go

Record events when Function， Builder, and Serving status change.

Add support for event record

---

pkg/core/serving/knative/servingrun.go

https://github.com/OpenFunction/OpenFunction/issues/485

Support to pass the annotation of Serving to Kantive Serving

---

pkg/core/serving/knative/servingrun.go

Reverts OpenFunction/OpenFunction#486

Revert "Support to pass the annotation of Serving to Kantive Serving"
